# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftNoStoryboards' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftNoStoryboards
  pod 'PureLayout'
  pod 'ReactiveCocoa', '~>4.2.2'
  pod 'XCGLogger', '~> 3.6.0'
  pod 'Rex', :git => 'https://github.com/RACCommunity/Rex', :tag => '0.12.0'

  target 'SwiftNoStoryboardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftNoStoryboardsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
