# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftNoStoryboards' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftNoStoryboards
  pod 'PureLayout'
  pod 'ReactiveCocoa', '~>2.1.2'

  target 'SwiftNoStoryboardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftNoStoryboardsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
